In [2]:
import numpy as np


# NumPy Kütüphanesi ve Kullanımı

NumPy, Python'da bilimsel hesaplamalar için kullanılan güçlü bir kütüphanedir. Çok boyutlu diziler (array'ler) ve matris işlemleri yapmaya olanak sağlar.

Bu çalışma, NumPy kütüphanesinin 10 farklı fonksiyonunu açıklamakta ve örneklerle göstermektedir.


### Fonksiyon 1: np.array()

In [3]:
# np.array() kullanımı
liste = [1, 2, 3, 4, 5]
dizi = np.array(liste)
print("NumPy Dizisi:", dizi)


NumPy Dizisi: [1 2 3 4 5]


### Fonksiyon 2: np.zeros()

In [4]:
# np.zeros() ile sıfırlarla dolu matris oluşturma
dizi = np.zeros((3, 3))
print(dizi)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Fonksiyon 3: np.ones()

In [5]:
# np.ones() ile birlerle dolu matris oluşturma
dizi = np.ones((2, 4))
print(dizi)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Fonksiyon 4: np.arange()

In [6]:

dizi = np.arange(0, 10, 2)
print(dizi)


[0 2 4 6 8]


### Fonksiyon 5: np.linspace()

In [7]:
# np.linspace() ile eşit aralıklı sayılar oluşturma
dizi = np.linspace(0, 1, 5)
print(dizi)


[0.   0.25 0.5  0.75 1.  ]


### Fonksiyon 6: np.random.rand()

In [8]:
# np.random.rand() ile rastgele sayı üretme
dizi = np.random.rand(3, 3)
print(dizi)


[[0.13211701 0.13274239 0.15105746]
 [0.17508692 0.79594285 0.10460753]
 [0.56301765 0.3686039  0.78925583]]


### Fonksiyon 7: np.reshape()

In [9]:
# np.reshape() ile diziyi yeniden şekillendirme
dizi = np.arange(9).reshape(3, 3)
print(dizi)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Fonksiyon 8: np.sum()

In [11]:
# np.sum() ile dizideki elemanların toplamını alma
dizi = np.array([1, 2, 3, 4, 5])
toplam = np.sum(dizi)
print("Toplam:", toplam)


Toplam: 15


### Fonksiyon 9: np.mean()

In [12]:
# np.mean() ile ortalama hesaplama
dizi = np.array([10, 20, 30, 40, 50])
ortalama = np.mean(dizi)
print("Ortalama:", ortalama)


Ortalama: 30.0


### Fonksiyon 10: np.sort()

In [13]:
# np.sort() ile diziyi sıralama
dizi = np.array([5, 3, 8, 1, 9])
sirali = np.sort(dizi)
print("Sıralı Dizi:", sirali)


Sıralı Dizi: [1 3 5 8 9]
